name: morphzing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Presentations library
  flutter_screenutil: ^5.3.1
  cupertino_icons: ^1.0.2
  simple_gradient_text: ^1.2.3
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.5+3
  carousel_slider: ^4.1.1
  social_share: ^2.2.1
  date_picker_timeline: ^1.2.3
  table_calendar: ^3.0.6
  dio: ^4.0.6
  connectivity_plus: ^2.3.7
  get: ^4.6.5
  path_provider: ^2.0.11
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  get_storage: ^2.0.3
  intl: ^0.17.0
  url_launcher: ^6.1.6
  flutter_time_picker_spinner: ^2.0.0
  painter: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_sound: ^9.2.13
  audio_waveforms: ^0.1.5+1
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.5


flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/lang/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#4890FF"


flutter_native_splash:
  image: "assets/icons/app_icon.png"
  android: true
  ios: true
  color: "#4890FF"
#  branding: "assets/icons/app_icon.png"


